"""Train a small local model and emit auditable metrics."""
from pathlib import Path
import json
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

ROOT = Path(__file__).resolve().parents[2]
DATA = ROOT / "data" / "processed" / "student_intervention_baseline.csv"
REPORT = ROOT / "reports"; TECH = ROOT / "technical-assurance"; MODEL = ROOT / "model-cards"; DATASET = ROOT / "dataset-cards"

def main():
    REPORT.mkdir(exist_ok=True); TECH.mkdir(exist_ok=True); MODEL.mkdir(exist_ok=True); DATASET.mkdir(exist_ok=True)
    df = pd.read_csv(DATA)
    features = ["age_band", "course", "attendance", "assessment_performance", "engagement", "prior_interventions", "support_need"]
    X, y = df[features], df.outcome
    cat = ["age_band", "course"]; num = [c for c in features if c not in cat]
    prep = ColumnTransformer([("cat", OneHotEncoder(handle_unknown="ignore"), cat), ("num", "passthrough", num)])
    pipe = Pipeline([("prep", prep), ("model", LogisticRegression(max_iter=500, random_state=42001))])
    Xtr, Xte, ytr, yte = train_test_split(X, y, test_size=.25, random_state=42001, stratify=y)
    pipe.fit(Xtr, ytr); pred = pipe.predict(Xte); prob = pipe.predict_proba(Xte)[:,1]
    metrics = {"dataset": "student_intervention_baseline.csv", "seed": 42001, "test_rows": len(yte),
               "accuracy": round(accuracy_score(yte,pred),4), "precision": round(precision_score(yte,pred,zero_division=0),4),
               "recall": round(recall_score(yte,pred,zero_division=0),4), "f1": round(f1_score(yte,pred,zero_division=0),4),
               "roc_auc": round(roc_auc_score(yte,prob),4), "decision_threshold": .5}
    (REPORT / "model-metrics.json").write_text(json.dumps(metrics, indent=2)+"\n")
    pd.DataFrame(confusion_matrix(yte,pred), index=["actual_0","actual_1"], columns=["pred_0","pred_1"]).to_csv(REPORT/"confusion-matrix.csv")
    (TECH / "performance-results.json").write_text(json.dumps({"status":"PASS", "metrics":metrics, "limitations":["synthetic data","not validated for deployment"]}, indent=2)+"\n")
    (MODEL / "student-intervention-model-card.md").write_text("""# Student Intervention Predictor - model card\n\nSynthetic logistic-regression demonstrator. It estimates a support-risk signal for triage only; it must not make a consequential decision without qualified human review. Training data and limitations are documented in the dataset card. Metrics are reproducible with the supplied script and are not evidence of production fitness.\n\n## Governance controls\n- documented purpose and prohibited uses\n- threshold review and subgroup testing\n- human review, contestability and escalation\n- versioned change approval and monitoring\n""")
    (DATASET / "student-intervention-dataset-card.md").write_text("""# Student Intervention Dataset Card\n\nAll records are deterministic synthetic records generated by `src/data_generation/generate_synthetic_data.py` with seed `42001`. No real students, identifiers or events are represented. Fields are limited to a fictional assurance scenario.\n\nThe baseline and drift datasets are deliberately different to exercise data-quality, fairness and monitoring controls. Protected/sensitive-style group fields are synthetic and used only for fairness testing.\n""")
    print(json.dumps(metrics, indent=2))
if __name__ == "__main__": main()
